# Generated by Django 5.0.6 on 2024-06-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mattapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
