# Generated by Django 5.0.7 on 2024-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattapp', '0002_rename_content_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name and Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Delivery Address')),
                ('pickup_option', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup in person')], default='delivery', max_length=10, verbose_name='Delivery or Pickup')),
                ('wants_hat', models.BooleanField(default=False, verbose_name='Do you want a hat?')),
            ],
        ),
    ]
