# Generated by Django 5.0.7 on 2024-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattapp', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wants_hat',
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='Kowalski', max_length=100, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
